### ISSUE TITLE
"Defined in" Should not exist on module pages

### ISSUE THREAD

**Issue by dangreenisrael** [offirgolan/yuidoc-ember-theme#3]
In the ember api docs, `Defined in` does not show up.

It does show up for modules this theme, but (at least in our case) with an erroneous link to the first class (not to the actual module definition)

Shall I include this fix in a PR?

**Comment by offirgolan** [comment]
@dangreenisrael I've noticed that before. I dont believe this to be a bug with this theme but an issue with yuidoc. As showing the `defined in` on a module is considered "standard", I think we should add an option (`hideModuleDefinedIn`) instead of just removing it altogether.

**Comment by dangreenisrael** [comment]
That makes sense,

I was thinking about adding options for:

- hideModuleDefinedIn
- hideTagLinkInSidebar

Thoughts?

**Comment by offirgolan** [comment]
@dangreenisrael those 2 work for me 😄
