### ISSUE TITLE
Theming/Branding Options

### ISSUE THREAD

**Issue by pzuraq** [offirgolan/yuidoc-ember-theme#4]
This YUIDoc theme is amazing! Was wondering if you would be open to adding just a few theme options. Very simple stuff, mainly being able to specify a custom logo to replace the Ember logo, and maybe a small color palette for the accent colors. I can work on it if your open to it, if not no worries!

**Comment by offirgolan** [comment]
@pzuraq yeah that sounds good to me. PRs are always welcome 😸
